#!/bin/bash
# Add an AUTHENTICATED path to the Lenovo's GarageFiles share so the Beast (Win11
# 24H2, which mandates SMB signing and thus refuses guest) can connect. A dedicated
# Samba service user 'hcc' - password generated by Claude, never Jeff's, stored in
# HCC-secrets. Guest access stays for the Acer; authenticated adds the Beast.
# Reads the generated password from /tmp/hccpw (scp'd separately, then deleted).
set -u
[ -f /tmp/hccpw ] || { echo "no /tmp/hccpw"; exit 1; }
PW=$(cat /tmp/hccpw)

echo "=== service user 'hcc' (no login shell, no home) ==="
id hcc >/dev/null 2>&1 || sudo useradd -M -s /usr/sbin/nologin hcc
printf '%s\n%s\n' "$PW" "$PW" | sudo smbpasswd -s -a hcc >/dev/null
sudo smbpasswd -e hcc >/dev/null
echo "  hcc samba user set"

echo "=== rewrite GarageFiles: guest (Acer) + authenticated (Beast), writes as jeffloewen ==="
sudo python3 - <<'PY'
import re
p='/etc/samba/smb.conf'
s=open(p).read()
s=re.sub(r'\n\[GarageFiles\][\s\S]*?(?=\n\[|\Z)','',s)
s=s.rstrip()+'''

[GarageFiles]
   comment = Lenovo files (garage laptop)
   path = /home/jeffloewen
   browseable = yes
   read only = no
   guest ok = yes
   force user = jeffloewen
   create mask = 0644
   directory mask = 0755
'''
open(p,'w').write(s)
PY
sudo systemctl restart smbd
rm -f /tmp/hccpw
echo "  smbd: $(systemctl is-active smbd)"
testparm -s 2>/dev/null | grep -E '\[GarageFiles\]|guest ok|force user' | sed 's/^/  /'
echo "done"
